css-brochure-form | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #15
Opened 2021-01-21 04:04 UTC by SamuelCho1

Used HTML and CSS to build a custom form.
<img width="502" alt="Screen Shot 2021-01-20 at 7 44 30 PM" src="https://user-images.githubusercontent.com/76749207/105278554-9df20400-5b5a-11eb-9868-19011d6e7deb.png">

2021-01-21 21:01 UTC, codingcodymiller requested changes
Hey Sam! Great work so far, please see my notes. Also, you might want to try removing duplication from the CSS by using grouped selectors where applicable, such as with font family.

2021-01-23 00:03 UTC, codingcodymiller requested changes
Hey Sam! You missed a comment from my review, please take a look 👀

2021-01-23 00:03 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 25%;
This has still not been addressed.

2021-01-23 19:09 UTC, SamuelCho1 commented
<img width="485" alt="Screen Shot 2021-01-23 at 11 08 17 AM" src="https://user-images.githubusercontent.com/76749207/105611667-6c03bc00-5d6b-11eb-8d42-0f2b6d59ad96.png">
<img width="215" alt="Screen Shot 2021-01-23 at 11 08 52 AM" src="https://user-images.githubusercontent.com/76749207/105611670-6c9c5280-5d6b-11eb-8eb1-a675ab28756b.png">

2021-01-26 02:39 UTC, codingcodymiller approved these changes
Nice work!!! 🎉

2021-01-26 05:24 UTC, merged