javascript-loops-practice | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #33
Opened 2021-01-28 22:55 UTC by SamuelCho1

Practiced the basics of JavaScript Loops.

2021-01-28 23:05 UTC, SamuelCho1 commented
<img width="1408" alt="Screen Shot 2021-01-28 at 1 26 42 PM" src="https://user-images.githubusercontent.com/76749207/106209626-33545000-617a-11eb-9a08-91457facb0be.png">
<img width="1427" alt="Screen Shot 2021-01-28 at 1 26 53 PM" src="https://user-images.githubusercontent.com/76749207/106209630-351e1380-617a-11eb-8e43-d014692a9392.png">
<img width="1419" alt="Screen Shot 2021-01-28 at 1 27 03 PM" src="https://user-images.githubusercontent.com/76749207/106209631-35b6aa00-617a-11eb-9f74-86429e2078c5.png">

2021-01-29 17:15 UTC, codingcodymiller requested changes
Hey Sam! One change for you, please see my note

2021-01-29 17:15 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
> +    }
This will only work if the last value in the array is `7`.

2021-01-29 19:01 UTC, SamuelCho1 commented
<img width="293" alt="Screen Shot 2021-01-29 at 10 57 30 AM" src="https://user-images.githubusercontent.com/76749207/106316235-3e15f000-6221-11eb-82b5-a977f716c582.png">
<img width="384" alt="Screen Shot 2021-01-29 at 10 57 36 AM" src="https://user-images.githubusercontent.com/76749207/106316237-3eae8680-6221-11eb-8955-6853763c3930.png">

2021-01-29 21:18 UTC, thebearingedge approved these changes

2021-01-30 21:01 UTC, merged