string-manipulation-1 | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #36
Opened 2021-01-29 23:00 UTC by SamuelCho1

JavaScript string manipulation practice with unit tests.

2021-01-29 23:01 UTC, SamuelCho1 commented
<img width="1403" alt="Screen Shot 2021-01-29 at 2 55 00 PM" src="https://user-images.githubusercontent.com/76749207/106336015-d6709c80-6242-11eb-8f71-c196a537f20d.png">
<img width="1398" alt="Screen Shot 2021-01-29 at 2 55 12 PM" src="https://user-images.githubusercontent.com/76749207/106336019-d83a6000-6242-11eb-98c4-f634fff36809.png">
<img width="1417" alt="Screen Shot 2021-01-29 at 2 55 23 PM" src="https://user-images.githubusercontent.com/76749207/106336021-d8d2f680-6242-11eb-849f-9d580329ea86.png">

2021-01-29 23:34 UTC, codingcodymiller requested changes
Nice work so far! please see my note

2021-01-29 23:34 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +  var String;
💀 💀 💀 💀 💀 

Avoid making variables that start with capital letters. `String` has special meaning in JavaScript, and **_you just blew it up_**. How about `words`?

2021-01-30 01:36 UTC, SamuelCho1 commented
<img width="374" alt="Screen Shot 2021-01-29 at 5 35 00 PM" src="https://user-images.githubusercontent.com/76749207/106343093-8ef50b00-6258-11eb-9638-ed90bdf781e1.png">

2021-01-30 01:39 UTC, thebearingedge approved these changes

2021-01-30 21:02 UTC, merged