array-manipulation-2 | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #47
Opened 2021-02-03 05:34 UTC by SamuelCho1

<img width="1413" alt="Screen Shot 2021-02-02 at 9 29 34 PM" src="https://user-images.githubusercontent.com/76749207/106703093-5fb70480-659e-11eb-8dd8-2e5937078651.png">
<img width="1422" alt="Screen Shot 2021-02-02 at 9 29 41 PM" src="https://user-images.githubusercontent.com/76749207/106703096-6180c800-659e-11eb-8234-718722dae206.png">

JavaScript array manipulation practice with unit tests.

2021-02-03 15:45 UTC, thebearingedge reviewed
Ok, in general try to avoid letting loops run if they don't need to.

2021-02-03 15:45 UTC, thebearingedge commented on array-manipulation-2/src/drop-right.js
> +  }
You can simplify this quite a bit. You should not need an `if/else`.

2021-02-03 15:45 UTC, thebearingedge commented on array-manipulation-2/src/drop.js
> +    }
You should not need an `if/else` for this. Try to simplify your solution. Think carefully about your initialization and condition expressions in the `for` loop.

2021-02-03 15:45 UTC, thebearingedge commented on array-manipulation-2/src/take-right.js
> +  }
The `if/else` in here is not necessary. Try to avoid even starting the loop at all if the array is empty.

2021-02-03 15:45 UTC, thebearingedge commented on array-manipulation-2/src/take.js
> +  }
Same

2021-02-03 15:49 UTC, thebearingedge requested changes
Please see my notes.

2021-02-06 23:29 UTC, SamuelCho1 commented
<img width="652" alt="Screen Shot 2021-02-06 at 3 27 33 PM" src="https://user-images.githubusercontent.com/76749207/107131975-262d1480-6890-11eb-9390-16d5c9a9cc0a.png">
<img width="530" alt="Screen Shot 2021-02-06 at 3 28 00 PM" src="https://user-images.githubusercontent.com/76749207/107131976-275e4180-6890-11eb-94d2-19fcee84f0af.png">
<img width="674" alt="Screen Shot 2021-02-06 at 3 28 15 PM" src="https://user-images.githubusercontent.com/76749207/107131978-275e4180-6890-11eb-9c68-48c5f6dedaa7.png">
<img width="567" alt="Screen Shot 2021-02-06 at 3 28 22 PM" src="https://user-images.githubusercontent.com/76749207/107131979-27f6d800-6890-11eb-9e61-5a14aa4fd17b.png">

2021-02-06 23:41 UTC, thebearingedge approved these changes

2021-02-07 22:20 UTC, merged