object-manipulation-2 | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #57
Opened 2021-02-07 22:18 UTC by SamuelCho1

JavaScript object manipulation practice with unit tests.

2021-02-07 22:18 UTC, SamuelCho1 commented
<img width="666" alt="Screen Shot 2021-02-07 at 2 16 36 PM" src="https://user-images.githubusercontent.com/76749207/107161130-67d0c480-694f-11eb-8829-bafbf177945b.png">

2021-02-08 21:08 UTC, thebearingedge requested changes

2021-02-08 21:08 UTC, thebearingedge commented on object-manipulation-2/src/omit.js
> +    }
Try this approach to simplify things a bit:

- for each `sourceKey` in `source`
  - for each `keys` at `i`
    - declare a boolean for whether this `sourceKey` is `toBeOmitted`
    - if `sourceKey` is equal to `keys` at `i`, then
      - this `sourceKey` is `toBeOmitted`
      - `break` out of this inner loop
  - if `sourceKey` is not `toBeOmitted`, then
    - assign `source` at `sourceKey` to your new object at `sourceKey`.

2021-02-08 21:08 UTC, thebearingedge commented on object-manipulation-2/src/pick.js
> +    }
This inner loop is not necessary, you can use `keys[keyIndex]` instead of your `property` variable.

2021-02-16 03:39 UTC, SamuelCho1 commented
<img width="391" alt="Screen Shot 2021-02-15 at 7 38 00 PM" src="https://user-images.githubusercontent.com/76749207/108015625-79f0d980-6fc5-11eb-9aec-12e46a2d9728.png">
<img width="490" alt="Screen Shot 2021-02-15 at 7 38 08 PM" src="https://user-images.githubusercontent.com/76749207/108015626-7bba9d00-6fc5-11eb-86c8-f1e1906c36ac.png">
<img width="688" alt="Screen Shot 2021-02-15 at 7 38 13 PM" src="https://user-images.githubusercontent.com/76749207/108015627-7c533380-6fc5-11eb-9f97-221cfb19a23a.png">

2021-02-16 03:40 UTC, thebearingedge approved these changes

2021-02-16 19:33 UTC, merged