array-manipulation-3 | Samuel Cho
SamuelCho1/c0121-code-solutions pull request #66
Opened 2021-02-19 04:55 UTC by SamuelCho1

JavaScript array manipulation practice with unit tests.
<img width="1290" alt="Screen Shot 2021-02-18 at 8 50 54 PM" src="https://user-images.githubusercontent.com/76749207/108459499-a312a380-722b-11eb-974f-6e0f9ac9876f.png">
<img width="1294" alt="Screen Shot 2021-02-18 at 8 51 02 PM" src="https://user-images.githubusercontent.com/76749207/108459501-a4dc6700-722b-11eb-9706-fc15e771825a.png">
<img width="1300" alt="Screen Shot 2021-02-18 at 8 51 20 PM" src="https://user-images.githubusercontent.com/76749207/108459503-a574fd80-722b-11eb-9f7b-aec8cb741d26.png">

2021-02-21 21:06 UTC, thebearingedge requested changes

2021-02-21 21:06 UTC, thebearingedge commented on array-manipulation-3/src/flatten.js
> +    if (typeof array[i] === 'object') {
This would be more reliable with `Array.isArray()`

2021-02-21 21:06 UTC, thebearingedge commented on array-manipulation-3/src/zip.js
> +  }
You could simplify this a bit by deciding which array is shorter and then writing the loop once.

```js
var length = Math.min(first.length, second.length);
```

2021-02-21 23:46 UTC, SamuelCho1 commented
<img width="506" alt="Screen Shot 2021-02-21 at 3 44 20 PM" src="https://user-images.githubusercontent.com/76749207/108642747-e8b5b300-745b-11eb-9420-ddc29921fab8.png">
<img width="608" alt="Screen Shot 2021-02-21 at 3 44 33 PM" src="https://user-images.githubusercontent.com/76749207/108642749-e94e4980-745b-11eb-9f10-2a9f1fa6f0bd.png">

2021-02-22 21:08 UTC, thebearingedge approved these changes

2021-02-23 03:35 UTC, merged